version: "3.3"
services:
  blockchain:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    command: -printtoconsole
      -rpcallowip=127.0.0.1
      -rpcbind=127.0.0.1
      -rpcuser=dev
      -rpcpassword=dev
      -rpcport=9494
    volumes:
      - ./bin/:/zcore
    ports:
      - "9494:9494"
      - "8333:8333"
      - "18332:18332"
      - "18333:18333"
      - "18443:18443"
      - "18444:18444"
      - "17293:17293"
    expose:
      - "9494"
      - "17293"
